server:
    port: 8080
    servlet:
        context-path: /test-app/v1
    shutdown: graceful
app:
  instance-id: ${random.uuid}

---
spring:
    profiles: db
    autoconfigure:
       include:
       - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
       - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    jpa:
      hibernate:
        ddl-auto: create
    datasource:
      url: jdbc:mysql://${DB_URL:localhost:3306}/test?autoReconnect=true&useSSL=false
      username: ${DB_USER:user}
      password: ${DB_PASSWORD:password}
      driverClassName: com.mysql.jdbc.Driver
---
spring:
    profiles: default
    autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
        - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    application:
        name: java-test-app
    lifecycle:
        timeout-per-shutdown-phase: 13s
logging:
    interval: 1000
    level:
        root: info
management:
    health:
        livenessstate:
            enabled: true
        readinessstate:
            enabled: true
    endpoint:
      health:
          probes:
            enabled: true
          group:
            liveness:
              include: livenessState
            readiness:
              include: readinessState
          show-components: always
          show-details: always
    metrics:
        tags:
            application: java-test-app
    endpoints:
        loggers:
            enabled: true
        web:
            exposure:
                include: health, info, env, loggers, metrics, prometheus, configprops
    server:
        port: 8080